# Generated by Django 3.1.4 on 2020-12-05 07:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonderi',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
